Emotion_Detection/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('authentification.urls')),
    path('', include('emotiondetector.urls', namespace='emotiondetector')),
    path('live/',include('live.urls', namespace='live')),
    path('upload/',include('upload.urls', namespace='upload')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

live/urls.py
from django.urls import path
from . import views
app_name = 'live'  # Add this line to specify the app name

urlpatterns = [
    path('', views.index, name='index'),
    path('video_feed/', views.video_feed, name='video_feed'),
]

live/models.py
from keras.models import model_from_json
from tensorflow.python.keras.backend import set_session
import numpy as np

import tensorflow as tf

# Set TensorFlow logging level to ERROR to suppress INFO and WARNING messages
tf.compat.v1.logging.set_verbosity(tf.compat.v1.logging.ERROR)

config = tf.compat.v1.ConfigProto()
config.gpu_options.per_process_gpu_memory_fraction = 0.15
session = tf.compat.v1.Session(config=config)
set_session(session)

class FacialExpressionModel(object):

    EMOTIONS_LIST = ["Angry", "Disgust", "Fear", "Happy", "Neutral", "Sad", "Surprise"]

    def __init__(self, model_json_file, model_weights_file):
        # load model from JSON file
        with open(model_json_file, "r") as json_file:
            loaded_model_json = json_file.read()
            self.loaded_model = model_from_json(loaded_model_json)

        # load weights into the new model
        self.loaded_model.load_weights(model_weights_file)

    def predict_emotion(self, img):
        global session
        set_session(session)
        self.preds = self.loaded_model.predict(img)
        return FacialExpressionModel.EMOTIONS_LIST[np.argmax(self.preds)]

live/views.py
from django.shortcuts import render
from django.http import StreamingHttpResponse
from live.cameras import VideoCamera
from django.contrib.auth.decorators import login_required


# Create your views here.
@login_required(login_url='login')  # Replace 'login' with the actual URL name of your login page
def index(request):
    return render(request, 'index.html')

def video_feed(request):
    return StreamingHttpResponse(gen(VideoCamera()), content_type="multipart/x-mixed-replace;boundary=frame")

def gen(camera):
    while True:
        frame = camera.get_frame()
        yield (b'--frame\r\n'
               b'Content-Type: image/jpeg\r\n\r\n' + frame + b'\r\n\r\n')

live/templates/index.html
{% extends "header.html" %}

{% load static %}

{% block content %}
  <body>
    <div class="container px-6 py-16 mx-auto">
      <div class="row align-items-center">
        <div class="col-lg-6">
          <div class="lg:max-w-lg">
            <h1 class="text-3xl font-semibold text-primary mb-4">Emotion <br><span class="text-primary">detection</span></h1>
            <p class="mt-3 text-gray-600">Imagine a system that can instantly recognize your emotions through your webcam. Our real-time emotion detection technology uses advanced algorithms to analyze your facial expressions, providing insights into your feelings. Whether you're smiling, frowning, or expressing surprise, we can detect it all, helping you understand your emotions better. Start the live video feed to see it in action!</p>
            <button id="start-button" class="btn btn-primary btn-block mt-6">Start Live</button>
            <button id="end-button" class="btn btn-danger btn-block mt-6" style="display: none;">End Live</button>
          </div>
        </div>
        <div class="col-lg-6 mt-6 mt-lg-0">
          <img id="bg" class="w-75" src="{% url 'live:video_feed' %}" style="display: none;">
        </div>
      </div>
    </div>    
  </body>
  

  <script>
    const startButton = document.getElementById("start-button");
    const endButton = document.getElementById("end-button");
    const image = document.getElementById("bg");

    // Check local storage for the initial state
    const initialState = localStorage.getItem('imageState');

    if (initialState === 'visible') {
      image.style.display = "block";
      startButton.style.display = "none";
      endButton.style.display = "block";
    } else {
      image.style.display = "none";
      startButton.style.display = "block";
      endButton.style.display = "none";
    }

    startButton.addEventListener("click", () => {
      image.style.display = "block";
      startButton.style.display = "none";
      endButton.style.display = "block";
      // Store the state in local storage
      localStorage.setItem('imageState', 'visible');
    });

    endButton.addEventListener("click", () => {
      image.style.display = "none";
      startButton.style.display = "block";
      endButton.style.display = "none";
      // Store the state in local storage
      localStorage.setItem('imageState', 'hidden');
    });
  </script>
{% endblock %}